### ISSUE TITLE
Getting the same error, even when applying the code given as an example in the documentary of the package

### ISSUE THREAD

**Issue by Paiela** [Nosferican/Econometrics.jl#86]
So I was trying to perform a statistical analysis using the package. This was my code:
`using CSV
using Econometrics

y = 5000
x = 1:y

t = CSV.read("data.csv",DataFrame)
t2 = CSV.read("data2.csv",DataFrame)
t.m = x

model1 = fit(EconometricModel,@formula(Time ~ m^2),t)`

The error I got was the following:
`ERROR: LoadError: MethodError: no method matching (::Polynomial{Float64, :x})(::Type{EconometricModel}, ::StatsModels.FormulaTerm{StatsModels.Term, StatsModels.FunctionTerm{…}}, ::DataFrame)
The object of type `Polynomial{Float64, :x}` exists, but no method is defined for this combination of argument types when trying to treat it as a callable object.`

I tried altering the code multiple times with no result. I then tried applying the code given in the documentary of the package, that is:
`using Econometrics
using RDatasets

data = RDatasets.dataset("Ecdat", "PSID")

model = fit(EconometricModel, # Indicates the default model
            @formula(log(Earnings) ~ Educatn + Age + Age^2), # formula
            data)`
            
which resulted in the identical error
ERROR: LoadError: MethodError: no method matching (::Polynomial{Float64, :x})(::Type{EconometricModel}, ::StatsModels.FormulaTerm{StatsModels.FunctionTerm{…}, Tuple{…}}, ::DataFrame)
The object of type `Polynomial{Float64, :x}` exists, but no method is defined for this combination of argument types when trying to treat it as a callable object. `

I think this is because of Julia's latest version on which I'm working on, i.e. v1.11.1.

**Comment by Nosferican** [comment]
I am trying to reproduce it:
> julia> versioninfo()
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i7-1250U
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 4 default, 0 interactive, 2 GC (on 12 virtual cores)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_VERSION = 1.11.1


> Status `/workspaces/Econometrics.jl/Project.toml`
  [336ed68f] CSV v0.10.15
  [324d7699] CategoricalArrays v0.10.8
  [31c24e10] Distributions v0.25.112
  [e30172f5] Documenter v1.7.0
  [1a297f60] FillArrays v1.13.0
  [f6369f11] ForwardDiff v0.10.36
  [692b3bcd] JLLWrappers v1.6.1
  [a7f614a8] MLJBase v1.7.0
  [e80e1ace] MLJModelInterface v1.11.0
  [429524aa] Optim v1.9.4
  [d96e819e] Parameters v0.12.3
  [ce6b1742] RDatasets v0.7.7
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.3
  [4c63d2b9] StatsFuns v1.3.2
  [3eaba693] StatsModels v0.7.4
  [ab02a1b2] TableOperations v1.2.0
  [bd369af6] Tables v1.12.0
  [44d3d7a6] Weave v0.10.12
  [b46f53ff] WooldridgeDatasets v0.1.4
  [37e2e46d] LinearAlgebra v1.11.0
  [de0858da] Printf v1.11.0
  [8dfed614] Test v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0

```
julia> model = fit(
           EconometricModel, # Indicates the default model
           @formula(log(Earnings) ~ Educatn + Age + Age^2), # formula
           data[data[!, :Earnings] .> 0, :]
       )
Continuous Response Model
Number of observations: 3652
Null Loglikelihood: -5696.23
Loglikelihood: -5671.17
R-squared: 0.0136
LR Test: 50.11 ∼ χ²(3) ⟹  Pr > χ² = 0.0000
Formula: log(Earnings) ~ 1 + Educatn + Age + (Age ^ 2)
Variance Covariance Estimator: OIM
────────────────────────────────────────────────────────────────────────────────────
                    PE           SE      t-value  Pr > |t|        2.50%       97.50%
────────────────────────────────────────────────────────────────────────────────────
(Intercept)   7.14834      0.957333      7.46693    <1e-12   5.27138     9.0253
Educatn       0.00370285   0.00111874    3.30984    0.0009   0.00150944  0.00589627
Age           0.0934537    0.0493985     1.89183    0.0586  -0.00339765  0.190305
Age ^ 2      -0.000918383  0.000628258  -1.46179    0.1439  -0.00215015  0.000313389
────────────────────────────────────────────────────────────────────────────────────
```
Could you share your environment (`Pkg.status()`/ `]st`)?

**Comment by Paiela** [comment]
Well I could but the problem has been somehow solved. I tried installing Julia's latest version through the MSI launcher, after which the code worked fine.
